site_name: Nimmake Docs
site_url: https://nimmake-docs.readthedocs.io/en/latest/

theme:
  name: readthedocs
  custom_dir: overrides

plugins:
  - search
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
          link: /en/latest/
          site_name: Nimmake Docs
        - locale: zh
          name: 中文
          link: /en/latest/zh/
          site_name: Nimmake 文档
          nav_translations:
            Home: 首页
            BasicUsage: 基本使用
            AdvancedUsage: 高级用法
            SourceCode: 源代码
            Contributing: 贡献
            Params: 参数
            About: 关于

nav:
  - Home: index.md
  - BasicUsage: usage.md
  - AdvancedUsage: advanced.md
  - SourceCode: source.md
  - Contributing: contributing.md
  - Params: params.md
  - About: about.md
